server:
  port: 8082  # Puerto en el que corre el API Gateway

spring:
  application:
    name: api-gateway  # Nombre del servicio registrado en Eureka
  main:
    web-application-type: reactive  # Necesario para WebFlux / Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Activa descubrimiento automático de rutas por nombre de servicio
          lower-case-service-id: true  # Usa nombres en minúscula desde Eureka
      routes:  # ✅ CORRECTO: routes está dentro de gateway
        - id: xml-deserializer-route
          uri: lb://xml-deserializer
          predicates:
            - Path=/api/transaction/receive
          filters:
            - StripPrefix=2  # Elimina /api/transaction → /receive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL del servidor Eureka
  instance:
    prefer-ip-address: true  # Muestra IP real
